from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[2]
main=(ROOT/'scripts/Main.gd').read_text(encoding='utf-8')
card=(ROOT/'scripts/CardActor.gd').read_text(encoding='utf-8')
syn=(ROOT/'scripts/SynergyDB.gd').read_text(encoding='utf-8')
app=(ROOT/'scripts/AppShell.gd').read_text(encoding='utf-8')
pc=(ROOT/'legacy_reference/game_engine.py').read_text(encoding='utf-8')
cards=(ROOT/'data/cards.json').read_text(encoding='utf-8')
checks=[]
def ok(name, cond):
    checks.append((name,bool(cond))); print(('[OK] ' if cond else '[FAIL] ')+name)
ok('267 Godot family table present', 'const FAMILIES' in syn and syn.count('["') >= 20)
ok('267 PC family constants present', 'SYNERGY_FAMILIES' in pc)
ok('268 trio = +20%', 'return 0.20' in syn and 'field_ids.size() == 3' in syn)
ok('269 family pair = +12.5%', 'best = maxf(best, 0.125)' in syn)
ok('270 explicit duo = +15%', 'best = maxf(best, 0.15)' in syn)
ok('271 Zetsu/Akatsuki = +15%', 'card_id == "zetsu"' in syn and 'AKATSUKI.has(other_id)' in syn and 'return 0.15' in syn)
ok('272 no stacking / best only', 'var best: float = 0.0' in syn and 'maxf(best' in syn)
ok('273 HP ratio preserved', 'var ratio: float = float(hp) / float(old_max)' in card and 'round(ratio * float(max_hp))' in card)
ok('273 synergy HP based on printed HP', 'definition_max_hp' in card and 'synergy_hp' in card)
ok('274 dynamic field refresh exists', 'func _refresh_synergies()' in main and 'SynergyDB.bonus_for' in main)
ok('274 team status always refreshes synergies', 'func _update_team_status()' in main and '_refresh_synergies()' in main)
ok('274 defeated actors lose synergy', 'if actor.defeated:' in main and 'actor.set_synergy_bonus(0.0)' in main)
ok('275 collection text search', 'collection_search_query' in app and 'func _on_collection_search_changed' in app)
ok('275 search includes name/id/element', 'str(data.get("name",""))' in app and 'str(data.get("element",""))' in app)
ok('276 collection role filters', 'collection_role_filters' in app and 'func _toggle_collection_role' in app)
ok('276 PC primary roles imported', 'CARD_ROLE_PRIMARY' in app and '"DPS"' in app and '"SOIGNEUR"' in app)
ok('276 advanced roles imported', 'CARD_ROLE_ADVANCED' in app and '"TRACKER"' in app and '"ANTI-DEFENSE"' in app)
ok('277 role badges/text on cards', 'short_roles' in app and '_role_label' in app)
ok('277 roles visible in detail', '"RÔLES  "' in app)
ok('278 synergies in long card sheet', '[b]SYNERGIES[/b]' in app and 'SynergyDB.description' in app)
ok('279 base/free/available status', 'BASE • GRATUITE • DISPONIBLE' in app)
ok('280 detail has independent ScrollContainer', 'scroll.position = rect.position + Vector2(16, 308)' in app and 'rich.custom_minimum_size' in app)
ok('280 collection result counter', 'collection_count_label' in app and 'résultat' in app)
ok('281 deck text search', 'deck_search_query' in app and 'func _on_deck_search_changed' in app)
ok('281 deck role filters', 'deck_role_filters' in app and 'func _toggle_deck_role' in app)
ok('282 deck catalog remains scrollable', 'deck_grid = GridContainer.new()' in app and 'scroll.size = Vector2(1040, 458)' in app)
ok('283 live total stars', '_deck_total_stars()' in app and '32.5★' in app)
ok('283 live tier counts', '_deck_star_count(3.5)' in app and '_deck_star_count(5.0)' in app)
ok('284 duplicate reason', 'Cette carte est déjà dans ton deck.' in app)
ok('284 full deck reason', 'Ton deck contient déjà 8 cartes.' in app)
ok('284 tier cap reason', 'Limite atteinte pour les %s★.' in app)
ok('284 total star reason', 'Cette carte dépasserait la limite de 32,5★.' in app)
ok('285 local deck remains separate from solo draft', 'user://yugito_deck.json' in app and 'PreBattleScene' in app)
ok('70 cards data still present', cards.count('"id"') >= 70)
ok('P36 metadata AppShell', 'PROTOTYPE 36 SYNERGY COLLECTION DECK' in app)
ok('P36 metadata Main', 'PROTOTYPE 36 SYNERGY COLLECTION DECK' in main)
fails=[n for n,v in checks if not v]
print(f'\nP36: {len(checks)-len(fails)}/{len(checks)} checks passed')
if fails:
    print('FAILED:', *fails, sep='\n- '); sys.exit(1)
